### ISSUE TITLE
Error: Cannot find module 'pdf-to-base64'

### ISSUE THREAD

**Issue by woj1965** [ShubhamBansal1997/pdf-to-base64#1]
I has installed your package, but when I try to use, I getting the message **Error: Cannot find module 'pdf-to-base64'**, checking node-modules I found, apparently all files.
Is there anything I need to do?

**Comment by GatoReno** [comment]
I'm the second one with this issue, such an honor :'3

**Comment by ShubhamBansal1997** [comment]
@woj1965 @Gatoreno Sorry it's just a little typo in the package.json for the main file.

Just updated the Code

Thanks for raising the Issue.
