### ISSUE TITLE
Error: [validTypePdf] == false

### ISSUE THREAD

**Issue by richietyler** [ShubhamBansal1997/pdf-to-base64#4]
@ShubhamBansal1997 thanks so much for this great package. I'm periodically getting the following error from an implementation:

[*] Occurent some error... [validTypePdf] == false

Can you provide any info on why that would occur?

**Comment by ShubhamBansal1997** [comment]
@richietyler Please elaborate.

**Comment by richietyler** [comment]
Hi @ShubhamBansal1997, thanks for getting back to me. The error was being passed in to your package from another function in my app. Appreciate yours throwing the error, because that pointed to me the actual problem.
